global:
  smtp_smarthost: 'smtp.server.com:587'
  smtp_from: 'alertmanager@chedoparti.com'
  smtp_auth_username: 'user@server.com'
  smtp_auth_password: 'password'

route:
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'devteam@chedoparti.com'
